PATCH http://localhost:3000/users/me/avatar
Content-Type: application/json

{
     "avatar": "https://i.pinimg.com/originals/0a/d4/4e/0ad44ebdf52a3168c52362afa1eb8fdb.jpg"
}

###
POST http://localhost:3000/cards
Content-Type: application/json

{
    "name": "newCard",
    "вывы": "https://img4.goodfon.ru/original/6000x4000/6/d4/poni-loshadka-priroda-lug-tsvety.jpg"
}

###
GET  http://localhost:3000/users
Content-Type: application/json


###
GET  http://localhost:3000/cards/62ee5a616a64bb636c22f
Content-Type: application/json

